services: 
    gunicorn:
        image: docker.pkg.github.com/kevinab168/twitter_clone/backend
        ports: 
            - "8000:8000"
        volumes:
            - backend_static:/twitter_clone/static
    frontend:
        build: ./twitter_frontend/twitter_clone_front
        volumes:
            - frontend_static:/twitter_frontend/dist
    nginx: 
        image: nginx
        ports: 
            - "80:80"
            - "443:443"
        volumes:
            - /etc/nginx:/etc/nginx
            - /etc/letsencrypt:/etc/letsencrypt
            - frontend_static:/usr/share/nginx/frontend_static
            - backend_static:/usr/share/nginx/backend_static
volumes: 
    backend_static:
    frontend_static:
