services: 
    gunicorn:
        image: docker.pkg.github.com/kevinab168/twitter_clone/backend
        ports: 
            - "8000:8000"
        volumes:
            - backend_static:/twitter_clone/static
    frontend: 
        image: docker.pkg.github.com/kevinab168/twitter_clone_front/frontend:latest
        ports: 
            - "80:80"
            - "443:443"
        volumes:
            - /etc/nginx:/etc/nginx
            - /etc/letsencrypt:/etc/letsencrypt
            - backend_static:/usr/share/nginx/backend_static
volumes: 
    backend_static:
